sudo: false

language: go

go:
  - "1.10.x"
#  - master

os:
  - linux

git:
  depth: 1

notifications:
  email: false

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - make test-all

cache:
  directories:
    - $GOPATH/pkg/dep