language: go

go:
  - "1.10.x"
  - master

os:
  - linux

sudo: false

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - $GOPATH/bin/dep ensure

script:
  - make test-all
