sudo: false

language: go

go:
  - "1.10.x"
#  - master

os:
  - linux

git:
  depth: 1

notifications:
  email: false

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

#install:
#  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
#  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script:
  - make test-all
